name: Python unittest

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ELM327-emulator~=3.0.0
      - name: Test with unittest
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          python3 -m unittest &>> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

